### ISSUE TITLE
Homes and Warps get reset for all players

### ISSUE THREAD

**Issue by RaphaelArctic** [Gunpowder-MC/GunpowderTeleport#1] opened 2020-08-25 12:59 UTC
All homes and warps got reset. It looks like this happened because of a server restart.

Latest log file (current server session): 
[2020-08-25-1.log](https://github.com/Gunpowder-MC/GunpowderTeleport/files/5123847/2020-08-25-1.log)

Second latest log file:
[2020-08-25-2.log](https://github.com/Gunpowder-MC/GunpowderTeleport/files/5123848/2020-08-25-2.log)

**Comment by Martmists-GH** [comment] 2020-08-25 15:21
It looks like a user has two homes with the same name. I'll look into how this happened, as this was a limitation introduced only recently.

**Comment by theonearon** [comment] 2020-09-11 11:52
any update on this? we have the same issue currently, I can't figure out the issue, and I'm considering just replacing the mod at this point sadly.

**Comment by Martmists-GH** [comment] 2020-09-11 11:55
The issue has been found and we'll be publishing an update soon :)

**Comment by theonearon** [comment] 2020-10-10 14:09
When can we expect the next update? Sry if I'm being cocky but it's been a month and the issue is still present. Every restart / crash resets the homes and it's kinda annoying.

**Comment by therealeldaria** [comment] 2021-04-11 18:29
This seems to be the reason, I got this when I tried to save a new with /sethome after moving to a new home.
Everything works until server reboots, then the home is reverted to the old one.

[18:25:13] [Gunpowder Database Thread/ERROR]: Error on Database Thread! Please report to the mod author if this is unexpected!
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: Home.owner, Home.homeName)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:70) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at io.github.gunpowder.modelhandlers.HomeHandler$newHome$1.invoke(HomeHandler.java:95) ~[gunpowder-teleport-1.0.3+gunpowder.0.3.6.mc.1.16.5.jar:?]
        at io.github.gunpowder.modelhandlers.HomeHandler$newHome$1.invoke(HomeHandler.java:40) ~[gunpowder-teleport-1.0.3+gunpowder.0.3.6.mc.1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1$value$1.invoke(GunpowderDatabase.java:53) ~[gunpowder-base-0.3.7+1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1$value$1.invoke(GunpowderDatabase.java:52) ~[gunpowder-base-0.3.7+1.16.5.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1.invoke(GunpowderDatabase.java:52) [gunpowder-base-0.3.7+1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1.invoke(GunpowderDatabase.java:44) [gunpowder-base-0.3.7+1.16.5.jar:?]
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [63267493-c56f-4f02-821f-75caeddac26e.jar:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: Home.owner, Home.homeName)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[059d91f8-b07e-42db-8586-1a322c365345.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[059d91f8-b07e-42db-8586-1a322c365345.jar:?]
        at org.sqlite.core.DB.execute(DB.java:854) ~[059d91f8-b07e-42db-8586-1a322c365345.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[059d91f8-b07e-42db-8586-1a322c365345.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[059d91f8-b07e-42db-8586-1a322c365345.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23) ~[1547a0a8-d9db-447c-8e65-6b63c3db862f.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:111) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:117) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:11) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61) ~[9db0dfd5-dac5-409c-8a25-83ace59ef0ce.jar:?]
        ... 20 more

**Comment by Martmists-GH** [comment] 2021-04-11 18:57
Seems to be an issue with deleting homes, I'll see if that needs a fix or is fixed in development next week

**Comment by therealeldaria** [comment] 2021-04-11 19:10
By the way the work around is to make sure to /deletehome before doing a new /sethome
Then there is no error in the log.

**Closed as completed** 2021-04-17 14:02 UTC
